[package]
name = "gemini_client_rs"
version = "0.1.0"
edition = "2021"
description = "A Rust client for Google Gemini API"
license = "MIT"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] } # For async requests
thiserror = "1.0" # For custom error types (optional, but good practice)
dotenvy = "0.15.7"
